apiVersion: v1
kind: Service
metadata:
  name: tiny-web-service
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: tiny-web-app
